### PR TITLE
aliases!!

### PR DESCRIPTION
**Pull request by sameerav**
sorry for the 10000 commits
basically i suck at life and i dont know how to debug on heroku so i kept pushing and then checking heroku logs LOL

@dhruhin review this??

### CODE REVIEW

**Comment by dhruhin** [comment]
Hi @sameerav who are you? What did you add?

**Comment by sameerav** [comment]
hater

**Comment by sameerav** [comment]
can u not be a hater

**Comment by dhruhin** [comment]
I am very sorry, but I am not familiar with your work.

**Pull request merged**
